export const EVENTS = [
  {
    id: 1,
    title: '캠핑용품 대할인전',
    description: '텐트, 침낭, 용품 등 최대 70% 할인',
    image: '/assets/discount.png',
    badge: 'HOT',
    badgeColor: 'bg-red-500',
    tags: ['최대 70% 할인', '무료배송'],
    tagColors: ['bg-red-50 text-red-600', 'bg-blue-50 text-blue-600'],
    deadline: '~8/31',
    daysLeft: 7,
    category: '할인',
  },
  {
    id: 2,
    title: '글램핑 무료체험',
    description: 'SNS 후기 작성 시 1박 무료 제공',
    image: '/assets/free_trial.png',
    badge: '체험',
    badgeColor: 'bg-green-500',
    tags: ['무료체험', 'SNS 이벤트'],
    tagColors: ['bg-green-50 text-green-600', 'bg-purple-50 text-purple-600'],
    deadline: '~9/15',
    daysLeft: 23,
    category: '체험',
  },
  {
    id: 3,
    title: '신규회원 혜택',
    description: '가입 즉시 5만원 쿠폰팩 증정',
    image: '/assets/new_member.png',
    badge: '신규',
    badgeColor: 'bg-blue-500',
    tags: ['5만원 쿠폰', '즉시발급'],
    tagColors: ['bg-blue-50 text-blue-600', 'bg-orange-50 text-orange-600'],
    deadline: '상시',
    daysLeft: null,
    category: '쿠폰',
  },
  {
    id: 4,
    title: '럭키드로우 이벤트',
    description: '캠핑용품 세트, 숙박권 등 푸짐한 경품',
    image: '/assets/lucky_draw.png',
    badge: '럭키드로우',
    badgeColor: 'bg-yellow-500',
    tags: ['경품 추첨', '1등 100만원'],
    tagColors: ['bg-yellow-50 text-yellow-600', 'bg-purple-50 text-purple-600'],
    deadline: '~8/25',
    daysLeft: 3,
    category: '경품',
  },
];

export const EVENT_CATEGORIES = ['전체', '할인', '체험', '경품', '쿠폰'];
