const navFiles = new Set([
  'index.html',
  'event.html',
  'settings.html',
  'surroundings.html',
  'mypage.html',
  'wishlist.html',
  'equipment.html',
  'recommend_season.html',
  'weather.html',
  'shop_list.html',
  'customer_service.html',
  'recommend_result_list.html',
]);

function withNav(file) {
  return navFiles.has(file);
}

export const legacyRoutes = [
  { path: '/', file: 'index.html', showBottomNav: withNav('index.html') },
  { path: '/index.html', file: 'index.html', showBottomNav: withNav('index.html') },
  { path: '/admin', file: 'admin.html', showBottomNav: withNav('admin.html') },
  { path: '/admin.html', file: 'admin.html', showBottomNav: withNav('admin.html') },
  { path: '/customer_service', file: 'customer_service.html', showBottomNav: withNav('customer_service.html') },
  { path: '/customer_service.html', file: 'customer_service.html', showBottomNav: withNav('customer_service.html') },
  { path: '/equipment', file: 'equipment.html', showBottomNav: withNav('equipment.html') },
  { path: '/equipment.html', file: 'equipment.html', showBottomNav: withNav('equipment.html') },
  { path: '/event', file: 'event.html', showBottomNav: withNav('event.html') },
  { path: '/event.html', file: 'event.html', showBottomNav: withNav('event.html') },
  { path: '/login', file: 'login.html', showBottomNav: withNav('login.html') },
  { path: '/login.html', file: 'login.html', showBottomNav: withNav('login.html') },
  { path: '/mypage', file: 'mypage.html', showBottomNav: withNav('mypage.html') },
  { path: '/mypage.html', file: 'mypage.html', showBottomNav: withNav('mypage.html') },
  { path: '/recomend_course_tmap', file: 'recomend_course_tmap.html', showBottomNav: withNav('recomend_course_tmap.html') },
  { path: '/recomend_course_tmap.html', file: 'recomend_course_tmap.html', showBottomNav: withNav('recomend_course_tmap.html') },
  { path: '/recommend', file: 'recommend.html', showBottomNav: withNav('recommend.html') },
  { path: '/recommend.html', file: 'recommend.html', showBottomNav: withNav('recommend.html') },
  { path: '/recommend_result_list', file: 'recommend_result_list.html', showBottomNav: withNav('recommend_result_list.html') },
  { path: '/recommend_result_list.html', file: 'recommend_result_list.html', showBottomNav: withNav('recommend_result_list.html') },
  { path: '/recommend_season', file: 'recommend_season.html', showBottomNav: withNav('recommend_season.html') },
  { path: '/recommend_season.html', file: 'recommend_season.html', showBottomNav: withNav('recommend_season.html') },
  { path: '/reservation', file: 'reservation.html', showBottomNav: withNav('reservation.html') },
  { path: '/reservation.html', file: 'reservation.html', showBottomNav: withNav('reservation.html') },
  { path: '/search', file: 'search.html', showBottomNav: withNav('search.html') },
  { path: '/search.html', file: 'search.html', showBottomNav: withNav('search.html') },
  { path: '/search_map', file: 'search_map.html', showBottomNav: withNav('search_map.html') },
  { path: '/search_map.html', file: 'search_map.html', showBottomNav: withNav('search_map.html') },
  { path: '/search_result', file: 'search_result.html', showBottomNav: withNav('search_result.html') },
  { path: '/search_result.html', file: 'search_result.html', showBottomNav: withNav('search_result.html') },
  { path: '/settings', file: 'settings.html', showBottomNav: withNav('settings.html') },
  { path: '/settings.html', file: 'settings.html', showBottomNav: withNav('settings.html') },
  { path: '/shop_detail', file: 'shop_detail.html', showBottomNav: withNav('shop_detail.html') },
  { path: '/shop_detail.html', file: 'shop_detail.html', showBottomNav: withNav('shop_detail.html') },
  { path: '/shop_list', file: 'shop_list.html', showBottomNav: withNav('shop_list.html') },
  { path: '/shop_list.html', file: 'shop_list.html', showBottomNav: withNav('shop_list.html') },
  { path: '/surroundings', file: 'surroundings.html', showBottomNav: withNav('surroundings.html') },
  { path: '/surroundings.html', file: 'surroundings.html', showBottomNav: withNav('surroundings.html') },
  { path: '/weather', file: 'weather.html', showBottomNav: withNav('weather.html') },
  { path: '/weather.html', file: 'weather.html', showBottomNav: withNav('weather.html') },
  { path: '/wishlist', file: 'wishlist.html', showBottomNav: withNav('wishlist.html') },
  { path: '/wishlist.html', file: 'wishlist.html', showBottomNav: withNav('wishlist.html') },
];
